---
- name: configurating...
  become: yes
  become_user: root
  with_items:
    - f: hazelcast.xml
      d: '{{orientdb_config_dir}}'
      m: '0600'
    - f: orientdb-server-config.xml
      d: '{{orientdb_config_dir}}'
      m: '0600'
    - f: default-distributed-db-config.json
      d: '{{orientdb_config_dir}}'
      m: '0600'
  template:
    owner: '{{orientdb_user}}'
    group: '{{orientdb_group}}'
    src: '{{item.f}}.j2'
    dest: '{{item.d}}/{{item.f}}'
    mode: '{{item.m}}'

- name: installing...
  include_tasks: '{{orientdb_installer | default("systemd")}}.yml'
