---
- name: install service
  become: yes
  become_user: root
  with_items:
    - f: orientdb.service
      d: /etc/systemd/system
      m: '0644'
  template:
    src: '{{item.f}}.j2'
    dest: '{{item.d}}/{{item.f}}'
    mode: '{{item.m}}'
  register: orientdb_service_unit

- name: systemctl daemon-reload
  become: yes
  become_user: root
  when: orientdb_service_unit is changed and orientdb_activate
  command: systemctl daemon-reload

- name: launch orientdb service
  become: yes
  become_user: root
  when: orientdb_activate
  service:
    name: orientdb
    state: started
    enabled: yes
